GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/62d8571b03528a64538759e0

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Project"
}

###
DELETE http://localhost:3000/subscribers/62d85d34f2e4666064b5c454

###

PATCH http://localhost:3000/subscribers/62d86095380a8b300aa462ad
Content-Type: application/json

{
    "name": "New Great Person"
}


// set up this to use rest client to do requests in vs code 
